### ISSUE TITLE
能把嗅探视频单独分割出来吗 这个根本看不懂

### ISSUE THREAD

**Issue by MiChongs** [qiusunshine/youtoo#1]

**Comment by wuge2019** [comment]
@qiusunshine 大佬，你看见这个issues的第一反应是什么

**Comment by qiusunshine** [comment]
所以？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月2日(周二) 晚上11:15
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qiusunshine/youtoo] 能把嗅探视频单独分割出来吗 这个根本看不懂 (Issue #1)




 
@qiusunshine 大佬，你看见这个issues的第一反应是什么

**Comment by wuge2019** [comment]
> 所以？
> [……](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年4月2日(周二) 晚上11:15 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [qiusunshine/youtoo] 能把嗅探视频单独分割出来吗 这个根本看不懂 (Issue #1) @qiusunshine 大佬，你看见这个issues的第一反应是什么 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

上去呼他两巴掌

**Comment by qiusunshine** [comment]
🤣



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月2日(周二) 晚上11:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qiusunshine/youtoo] 能把嗅探视频单独分割出来吗 这个根本看不懂 (Issue #1)




  
所以？
 ……
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年4月2日(周二) 晚上11:15 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [qiusunshine/youtoo] 能把嗅探视频单独分割出来吗 这个根本看不懂 (Issue #1) @qiusunshine 大佬，你看见这个issues的第一反应是什么 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.***&gt;
  
上去呼他两巴掌
